import { ColorCard, createColorCard } from './color-card.mjs';
import { Color, generateRandomColor } from './color.mjs';

/**
 * @callback GenerateColorCardsFn
 * @param {...Color} seedColors colors to generate the theme around
 * @returns {ColorCard[]} color cards generated by the theme
 */

/**
 * @typedef Theme
 * @property {string} name name of the theme (e.g. "analagous")
 * @property {GenerateColorCardsFn} generateColorCards
 *           function for generating color cards for the theme
 */

/**
 * Generates a theme with random colors.
 *
 * @param {Color[]} seedColors
 * @param {number} colorCount number of colors to return
 * @returns {Theme}
 */
function _randomTheme(colorCount) {
  return {
    name: `random-${colorCount}`,
    generateColorCards: (...seedColors) => {
      const colorCards = seedColors
        .slice(0, colorCount)
        .map(color => createColorCard(color.hex, 'Seed Color'));
      if (colorCards.length > 0) {
        colorCards[0].setEditable(`random-${colorCount}`);
      }

      let addedToBack = false;
      while (colorCards.length < colorCount) {
        const colorCard = createColorCard(
          generateRandomColor().hex,
          'Random Color'
        );

        // Alternately insert color cards into the front and back of the array
        // so that the seed colors would show up in the middle.
        if (addedToBack) {
          colorCards.splice(0, 0, colorCard);
        } else {
          colorCards.push(colorCard);
        }
        addedToBack = !addedToBack;
      }

      return colorCards;
    },
  };
}

/** @type {Object.<string, Theme>} */
export const Theme = {
  randomThreeTheme: _randomTheme(3),
  randomNineTheme: _randomTheme(9),
};

/**
 * @param {string} themeName
 * @returns {Theme}
 */
export function getTheme(themeName) {
  return Object.values(Theme).find(theme => theme.name === themeName);
}
