import { monochromaticTheme } from './themes/monochromatic-theme.mjs';
import { randomTheme } from './themes/random-theme.mjs';

/**
 * @callback GenerateColorCardsFn
 * @param {...Color} seedColors colors to generate the theme around
 * @returns {ColorCard[]} color cards generated by the theme
 */

/**
 * @typedef Theme
 * @property {string} name name of the theme (e.g. "analagous")
 * @property {GenerateColorCardsFn} generateColorCards
 *           function for generating color cards for the theme
 */

/** @type {Theme[]} */
export const THEMES = [
  randomTheme(3),
  randomTheme(5),
  randomTheme(9),
  randomTheme(16),
  monochromaticTheme(3),
  monochromaticTheme(5),
  monochromaticTheme(9),
];

/**
 * @param {string} themeName
 * @returns {Theme}
 */
export function getTheme(themeName) {
  return THEMES.find(theme => theme.name === themeName);
}
