import { ColorCard, createColorCard } from '../color-card.mjs';
import { Color } from '../color.mjs';

/**
 * Generates a theme with monochromatic colors.
 *
 * @param {number} colorCount number of colors to return
 * @returns {Theme}
 */
export function monochromaticTheme(colorCount) {
  return {
    name: `monochromatic-${colorCount}`,
    generateColorCards: (...seedColors) =>
      _generateColorCards(colorCount, seedColors[0]),
  };
}

/**
 * @param {number} colorCount number of colors to return
 * @param {Color} seedColor color to generate the theme around
 * @returns {ColorCard[]} color cards generated by the theme
 */
function _generateColorCards(colorCount, seedColor) {
  const seedColorCard = createColorCard(seedColor.hex, 'Seed Color');
  seedColorCard.setEditable(`monochromatic-${colorCount}`);

  const lightnessDiff = Math.max(
    20,
    Math.floor(
      Math.random() * Math.min(seedColor.hsl.l, 100 - seedColor.hsl.l)
    ) / (colorCount === 9 ? 2 : 1)
  );

  const lighterHexColor = colorCrafter.lighten(seedColor.hex, lightnessDiff);
  const darkerHexColor = colorCrafter.darken(seedColor.hex, lightnessDiff);

  const lighterColorCard = createColorCard(lighterHexColor, 'Lighter Color');
  const darkerColorCard = createColorCard(darkerHexColor, 'Darker Color');

  if (colorCount === 3) {
    return [lighterColorCard, seedColorCard, darkerColorCard];
  }

  if (colorCount === 5) {
    return [
      lighterColorCard,
      createColorCard(
        colorCrafter.lighten(seedColor.hex, lightnessDiff / 2),
        'Medium Light'
      ),
      seedColorCard,
      createColorCard(
        colorCrafter.darken(seedColor.hex, lightnessDiff / 2),
        'Medium Dark'
      ),
      darkerColorCard,
    ];
  }

  const saturationDiff = Math.max(
    40,
    Math.floor(Math.random() * Math.min(seedColor.hsl.s, 100 - seedColor.hsl.s))
  );

  const lighterDesaturatedHexColor = colorCrafter.desaturate(
    lighterHexColor,
    saturationDiff
  );
  const desaturatedHexColor = colorCrafter.desaturate(
    seedColor.hex,
    saturationDiff
  );
  const darkerDesaturatedHexColor = colorCrafter.desaturate(
    darkerHexColor,
    saturationDiff
  );

  const lighterSaturatedHexColor = colorCrafter.saturate(
    lighterHexColor,
    saturationDiff
  );
  const saturatedHexColor = colorCrafter.saturate(
    seedColor.hex,
    saturationDiff
  );
  const darkerSaturatedHexColor = colorCrafter.saturate(
    darkerHexColor,
    saturationDiff
  );

  return [
    createColorCard(lighterDesaturatedHexColor, 'Lighter Desaturated'),
    createColorCard(desaturatedHexColor, 'Desaturated'),
    createColorCard(darkerDesaturatedHexColor, 'Darker Desaturated'),
    lighterColorCard,
    seedColorCard,
    darkerColorCard,
    createColorCard(lighterSaturatedHexColor, 'Lighter Saturated'),
    createColorCard(saturatedHexColor, 'Saturated'),
    createColorCard(darkerSaturatedHexColor, 'Darker Saturated'),
  ];
}
