import { ColorCard, createColorCard } from '../color-card.mjs';
import { Color, generateRandomColor } from '../color.mjs';

/**
 * Generates a theme with random colors.
 *
 * @param {number} colorCount number of colors to return
 * @returns {Theme}
 */
export function randomTheme(colorCount) {
  return {
    name: `random-${colorCount}`,
    generateColorCards: (...seedColors) =>
      _generateColorCards(colorCount, ...seedColors),
  };
}

/**
 * @param {number} colorCount number of colors to return
 * @param {...Color} seedColors colors to generate the theme around
 * @returns {ColorCard[]} color cards generated by the theme
 */
function _generateColorCards(colorCount, ...seedColors) {
  const colorCards = seedColors
    .slice(0, colorCount)
    .map(color => createColorCard(color.hex, 'Seed Color'));
  if (colorCards.length > 0) {
    colorCards[0].setEditable(`random-${colorCount}`);
  }

  while (colorCards.length < colorCount) {
    const colorCard = createColorCard(
      generateRandomColor().hex,
      'Random Color'
    );
    colorCards.push(colorCard);
  }

  return colorCards;
}
